-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-yaml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: no-commit-to-branch #does not allow commit to master