language: generic
dist: xenial

before_install:
- sudo apt-get update
- sudo apt-get install unzip
- wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
- unzip terraform_0.11.11_linux_amd64.zip
- sudo install terraform /usr/local/bin/

script:
- ./deploy.sh

after_script:
- ./destroy.sh